// Advanced Reliability Engineering Center v6.0
// Inspired by Gremlin Chaos Engineering + Datadog/New Relic Synthetic Monitoring + Netflix Reliability
import { useState, useEffect } from 'react';

const AdvancedReliabilityEngineeringCenter = () => {
  const [chaosExperiments, setChaosExperiments] = useState([
    { 
      id: 'exp-001', 
      name: 'CPU Stress Test', 
      target: 'content-processor', 
      status: 'Running', 
      progress: 67, 
      duration: '5m 12s',
      impact: 'Minimal',
      blastRadius: 'Single Pod'
    },
    { 
      id: 'exp-002', 
      name: 'Network Latency Injection', 
      target: 'ai-agent-network', 
      status: 'Scheduled', 
      progress: 0, 
      duration: 'Pending',
      impact: 'Low',
      blastRadius: 'Service Mesh'
    },
    { 
      id: 'exp-003', 
      name: 'Memory Exhaustion', 
      target: 'intelligence-engine', 
      status: 'Completed', 
      progress: 100, 
      duration: '8m 45s',
      impact: 'Moderate',
      blastRadius: 'Namespace'
    },
    { 
      id: 'exp-004', 
      name: 'Disk Failure Simulation', 
      target: 'analytics-pipeline', 
      status: 'Failed', 
      progress: 25, 
      duration: '2m 13s',
      impact: 'High',
      blastRadius: 'Node'
    }
  ]);

  const [syntheticMonitoring, setSyntheticMonitoring] = useState([
    { 
      check: 'User Login Journey', 
      location: 'US-East', 
      status: 'Healthy', 
      uptime: 99.94, 
      responseTime: 234, 
      lastCheck: '30s ago',
      trend: 'stable'
    },
    { 
      check: 'API Health Check', 
      location: 'EU-West', 
      status: 'Healthy', 
      uptime: 99.87, 
      responseTime: 156, 
      lastCheck: '45s ago',
      trend: 'improving'
    },
    { 
      check: 'Content Processing Flow', 
      location: 'AP-Southeast', 
      status: 'Warning', 
      uptime: 98.23, 
      responseTime: 567, 
      lastCheck: '1m ago',
      trend: 'declining'
    },
    { 
      check: 'Dashboard Availability', 
      location: 'US-West', 
      status: 'Healthy', 
      uptime: 99.96, 
      responseTime: 89, 
      lastCheck: '15s ago',
      trend: 'stable'
    }
  ]);

  const [reliabilityScores, setReliabilityScores] = useState({
    overall: 94.7,
    chaos: 92.3,
    synthetic: 96.1,
    sla: 99.2,
    resilience: 91.8,
    availability: 99.87,
    performance: 94.5,
    recovery: 96.3
  });

  const [autoGeneratedTests, setAutoGeneratedTests] = useState([
    { 
      trigger: 'High CPU Alert', 
      generated: 'CPU Stress Chaos Test', 
      confidence: 87.3, 
      status: 'Ready',
      estimatedImpact: 'Low'
    },
    { 
      trigger: 'API Latency Spike', 
      generated: 'Network Partition Test', 
      confidence: 94.1, 
      status: 'Scheduled',
      estimatedImpact: 'Medium'
    },
    { 
      trigger: 'Memory Usage Pattern', 
      generated: 'Memory Leak Simulation', 
      confidence: 78.9, 
      status: 'Analyzing',
      estimatedImpact: 'High'
    },
    { 
      trigger: 'Error Rate Anomaly', 
      generated: 'Service Failure Test', 
      confidence: 91.7, 
      status: 'Ready',
      estimatedImpact: 'Medium'
    }
  ]);

  const [chaosTimeline, setChaosTimeline] = useState([
    { time: '09:00:15', event: 'CPU stress experiment started on content-processor', type: 'start', severity: 'info' },
    { time: '08:58:22', event: 'Memory exhaustion test completed successfully', type: 'completion', severity: 'success' },
    { time: '08:55:45', event: 'Disk failure simulation triggered service failover', type: 'impact', severity: 'warning' },
    { time: '08:52:10', event: 'Network latency injection scheduled for 09:15', type: 'schedule', severity: 'info' },
    { time: '08:48:33', event: 'Auto-generated chaos test approved for execution', type: 'approval', severity: 'info' }
  ]);

  const [resilientArchitecture, setResilientArchitecture] = useState({
    circuitBreakers: { active: 12, triggered: 2, success: 94.7 },
    bulkheads: { isolated: 8, breached: 0, isolation: 100.0 },
    retryLogic: { attempts: 1247, successful: 1189, rate: 95.3 },
    timeouts: { configured: 23, triggered: 5, effectiveness: 78.3 },
    fallbacks: { available: 15, used: 3, coverage: 89.1 },
    loadShedding: { events: 7, successful: 6, protection: 85.7 }
  });

  const [gamedays, setGamedays] = useState([
    { 
      name: 'Q1 Disaster Recovery', 
      date: '2026-03-20', 
      status: 'Upcoming', 
      participants: 23, 
      scenarios: 5,
      preparedness: 87.3
    },
    { 
      name: 'Database Outage Simulation', 
      date: '2026-02-28', 
      status: 'Completed', 
      participants: 18, 
      scenarios: 3,
      preparedness: 92.1
    },
    { 
      name: 'Network Split-Brain Test', 
      date: '2026-02-15', 
      status: 'Completed', 
      participants: 15, 
      scenarios: 4,
      preparedness: 89.7
    }
  ]);

  const [blastRadiusMetrics, setBlastRadiusMetrics] = useState({
    contained: 89.3,
    serviceMesh: 7.8,
    nodeLevel: 2.1,
    clusterWide: 0.8,
    averageRadius: 'Pod Level',
    isolationScore: 94.6
  });

  useEffect(() => {
    // Update chaos experiments
    const chaosInterval = setInterval(() => {
      setChaosExperiments(prev => prev.map(exp => {
        if (exp.status === 'Running') {
          const newProgress = Math.min(100, exp.progress + Math.random() * 5);
          return {
            ...exp,
            progress: newProgress,
            status: newProgress >= 100 ? 'Completed' : 'Running'
          };
        }
        return exp;
      }));
    }, 3000);

    // Update synthetic monitoring
    const syntheticInterval = setInterval(() => {
      setSyntheticMonitoring(prev => prev.map(check => ({
        ...check,
        uptime: Math.max(95, Math.min(99.99, check.uptime + (Math.random() - 0.3) * 0.1)),
        responseTime: Math.max(50, check.responseTime + (Math.random() - 0.5) * 50),
        status: check.responseTime > 500 ? 'Warning' : check.uptime < 98 ? 'Critical' : 'Healthy'
      })));
    }, 5000);

    // Update reliability scores
    const reliabilityInterval = setInterval(() => {
      setReliabilityScores(prev => ({
        overall: Math.max(85, Math.min(98, prev.overall + (Math.random() - 0.3) * 2)),
        chaos: Math.max(80, Math.min(95, prev.chaos + (Math.random() - 0.4) * 2)),
        synthetic: Math.max(90, Math.min(99, prev.synthetic + (Math.random() - 0.2) * 1.5)),
        sla: Math.max(95, Math.min(99.9, prev.sla + (Math.random() - 0.3) * 0.5)),
        resilience: Math.max(85, Math.min(96, prev.resilience + (Math.random() - 0.4) * 1.8)),
        availability: Math.max(99, Math.min(99.99, prev.availability + (Math.random() - 0.3) * 0.05)),
        performance: Math.max(88, Math.min(97, prev.performance + (Math.random() - 0.3) * 1.5)),
        recovery: Math.max(90, Math.min(98, prev.recovery + (Math.random() - 0.3) * 1.2))
      }));
    }, 7000);

    // Add new timeline events
    const timelineInterval = setInterval(() => {
      const events = [
        { event: 'Chaos experiment auto-generated from anomaly detection', type: 'generation', severity: 'info' },
        { event: 'Synthetic test detected performance regression', type: 'detection', severity: 'warning' },
        { event: 'Circuit breaker triggered due to high error rate', type: 'protection', severity: 'warning' },
        { event: 'System recovered from chaos experiment within SLA', type: 'recovery', severity: 'success' },
        { event: 'Resilience pattern activated successfully', type: 'activation', severity: 'info' }
      ];

      const newEvent = {
        time: new Date().toLocaleTimeString(),
        ...events[Math.floor(Math.random() * events.length)]
      };

      setChaosTimeline(prev => [newEvent, ...prev.slice(0, 9)]);
    }, 12000);

    return () => {
      clearInterval(chaosInterval);
      clearInterval(syntheticInterval);
      clearInterval(reliabilityInterval);
      clearInterval(timelineInterval);
    };
  }, []);

  const getStatusColor = (status) => {
    switch(status?.toLowerCase()) {
      case 'healthy': case 'completed': case 'success': case 'ready': return '#10B981';
      case 'warning': case 'running': case 'scheduled': case 'analyzing': return '#F59E0B';
      case 'critical': case 'failed': case 'error': return '#EF4444';
      case 'info': case 'pending': case 'upcoming': return '#3B82F6';
      default: return '#6B7280';
    }
  };

  const getSeverityIcon = (severity) => {
    switch(severity) {
      case 'critical': return '💥';
      case 'warning': return '⚠️';
      case 'info': return 'ℹ️';
      case 'success': return '✅';
      default: return '📊';
    }
  };

  const getImpactColor = (impact) => {
    switch(impact?.toLowerCase()) {
      case 'minimal': case 'low': return '#10B981';
      case 'moderate': case 'medium': return '#F59E0B';
      case 'high': case 'critical': return '#EF4444';
      default: return '#6B7280';
    }
  };

  return (
    <div className="space-y-6 font-mono text-sm">
      {/* Advanced Reliability Header */}
      <div className="bg-gray-900 rounded-lg border-2 border-red-500 p-6">
        <div className="text-center mb-6">
          <h1 className="text-3xl font-bold text-red-400 mb-2">ADVANCED RELIABILITY ENGINEERING CENTER</h1>
          <div className="text-lg text-white">Chaos Engineering + Synthetic Monitoring + Netflix Resilience • v6.0</div>
          <div className="text-sm text-red-300 mt-2">Failure Injection • Auto-Generated Tests • Resilient Architecture • Game Days</div>
        </div>
        
        {/* Reliability Scores */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {Object.entries(reliabilityScores).map(([key, value]) => (
            <div key={key} className="bg-red-900 rounded p-4 border border-red-400">
              <div className="text-center">
                <div className="text-red-400 text-xs mb-1 uppercase">
                  {key === 'sla' ? 'SLA' : key.replace(/([A-Z])/g, ' $1').trim()}
                </div>
                <div className="text-lg font-bold text-white">
                  {key.includes('availability') || key.includes('sla') ? `${value.toFixed(2)}%` : `${value.toFixed(1)}`}
                </div>
                <div className="w-full bg-gray-600 rounded-full h-1.5 mt-2">
                  <div 
                    className="h-full bg-gradient-to-r from-red-500 to-orange-500 rounded-full"
                    style={{ width: `${key.includes('availability') || key.includes('sla') ? (value - 95) * 20 : value}%` }}
                  />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Chaos Experiments */}
        <div className="bg-gray-800 rounded-lg p-6 border border-gray-600">
          <h3 className="text-lg font-bold text-white mb-4">💥 Chaos Engineering Experiments</h3>
          
          <div className="space-y-3">
            {chaosExperiments.map((exp, index) => (
              <div key={index} className="bg-gray-700 rounded p-3 border border-gray-600">
                <div className="flex justify-between items-center mb-2">
                  <div>
                    <div className="text-white font-bold text-sm">{exp.name}</div>
                    <div className="text-gray-400 text-xs">{exp.target} • {exp.blastRadius}</div>
                  </div>
                  <div className="text-right">
                    <div 
                      className="text-xs font-bold"
                      style={{ color: getStatusColor(exp.status) }}
                    >
                      ● {exp.status.toUpperCase()}
                    </div>
                    <div 
                      className="text-xs"
                      style={{ color: getImpactColor(exp.impact) }}
                    >
                      Impact: {exp.impact}
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center justify-between">
                  <div className="flex-1 mr-3">
                    <div className="bg-gray-600 rounded-full h-2 overflow-hidden">
                      <div 
                        className="h-full transition-all duration-1000 rounded-full"
                        style={{ 
                          width: `${exp.progress}%`,
                          backgroundColor: getStatusColor(exp.status)
                        }}
                      />
                    </div>
                  </div>
                  <div className="text-xs text-gray-300">{exp.duration}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Synthetic Monitoring */}
        <div className="bg-gray-800 rounded-lg p-6 border border-gray-600">
          <h3 className="text-lg font-bold text-white mb-4">🔍 Synthetic Monitoring</h3>
          
          <div className="space-y-3">
            {syntheticMonitoring.map((check, index) => (
              <div key={index} className="bg-gray-700 rounded p-3 border border-gray-600">
                <div className="flex justify-between items-center mb-2">
                  <div>
                    <div className="text-white font-bold text-sm">{check.check}</div>
                    <div className="text-gray-400 text-xs">{check.location} • {check.lastCheck}</div>
                  </div>
                  <div className="text-right">
                    <div 
                      className="text-xs font-bold"
                      style={{ color: getStatusColor(check.status) }}
                    >
                      ● {check.status.toUpperCase()}
                    </div>
                    <div className="text-xs text-gray-400">{check.trend}</div>
                  </div>
                </div>
                
                <div className="grid grid-cols-2 gap-3 text-xs">
                  <div className="text-center">
                    <div className="text-white font-bold">{check.uptime.toFixed(2)}%</div>
                    <div className="text-gray-400">Uptime</div>
                  </div>
                  <div className="text-center">
                    <div className="text-white font-bold">{check.responseTime}ms</div>
                    <div className="text-gray-400">Response</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Auto-Generated Tests */}
      <div className="bg-gray-800 rounded-lg p-6 border border-gray-600">
        <h3 className="text-lg font-bold text-white mb-4">🤖 AI-Generated Reliability Tests</h3>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {autoGeneratedTests.map((test, index) => (
            <div key={index} className="bg-gray-700 rounded p-3 border border-gray-600">
              <div className="flex justify-between items-center mb-2">
                <div>
                  <div className="text-white font-medium text-sm">{test.generated}</div>
                  <div className="text-gray-400 text-xs">Triggered by: {test.trigger}</div>
                </div>
                <div className="text-right">
                  <div 
                    className="text-xs font-bold"
                    style={{ color: getStatusColor(test.status) }}
                  >
                    {test.status.toUpperCase()}
                  </div>
                  <div 
                    className="text-xs"
                    style={{ color: getImpactColor(test.estimatedImpact) }}
                  >
                    {test.estimatedImpact} Impact
                  </div>
                </div>
              </div>
              
              <div className="flex justify-between items-center text-xs">
                <span className="text-gray-300">Confidence: {test.confidence.toFixed(1)}%</span>
                <div className="w-16 bg-gray-600 rounded-full h-1.5">
                  <div 
                    className="h-full bg-blue-500 rounded-full"
                    style={{ width: `${test.confidence}%` }}
                  />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Resilient Architecture Patterns */}
        <div className="bg-gray-800 rounded-lg p-6 border border-gray-600">
          <h3 className="text-lg font-bold text-white mb-4">🛡️ Resilient Architecture Patterns</h3>
          
          <div className="space-y-3">
            {Object.entries(resilientArchitecture).map(([pattern, data], index) => (
              <div key={index} className="bg-gray-700 rounded p-3 border border-gray-600">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-white font-medium capitalize">
                    {pattern.replace(/([A-Z])/g, ' $1').trim()}
                  </span>
                  <div className="text-right">
                    {data.success && (
                      <div className="text-white font-bold text-sm">{data.success.toFixed(1)}%</div>
                    )}
                    {data.rate && (
                      <div className="text-white font-bold text-sm">{data.rate.toFixed(1)}%</div>
                    )}
                    {data.isolation && (
                      <div className="text-white font-bold text-sm">{data.isolation.toFixed(1)}%</div>
                    )}
                  </div>
                </div>
                
                <div className="grid grid-cols-3 gap-2 text-xs text-gray-300">
                  {Object.entries(data).map(([key, value], idx) => (
                    <div key={idx} className="text-center">
                      <div className="font-medium">{typeof value === 'number' ? value.toFixed(0) : value}</div>
                      <div className="text-gray-400 capitalize">{key}</div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Game Days & Disaster Recovery */}
        <div className="space-y-6">
          <div className="bg-gray-800 rounded-lg p-6 border border-gray-600">
            <h3 className="text-lg font-bold text-white mb-4">🎮 Game Days</h3>
            
            <div className="space-y-3">
              {gamedays.map((gameday, index) => (
                <div key={index} className="bg-gray-700 rounded p-3 border border-gray-600">
                  <div className="flex justify-between items-center mb-2">
                    <div>
                      <div className="text-white font-medium text-sm">{gameday.name}</div>
                      <div className="text-gray-400 text-xs">{gameday.date}</div>
                    </div>
                    <div 
                      className="text-xs font-bold"
                      style={{ color: getStatusColor(gameday.status) }}
                    >
                      {gameday.status.toUpperCase()}
                    </div>
                  </div>
                  
                  <div className="grid grid-cols-3 gap-2 text-xs">
                    <div className="text-center">
                      <div className="text-white font-medium">{gameday.participants}</div>
                      <div className="text-gray-400">Participants</div>
                    </div>
                    <div className="text-center">
                      <div className="text-white font-medium">{gameday.scenarios}</div>
                      <div className="text-gray-400">Scenarios</div>
                    </div>
                    <div className="text-center">
                      <div className="text-white font-medium">{gameday.preparedness.toFixed(1)}%</div>
                      <div className="text-gray-400">Readiness</div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-gray-800 rounded-lg p-6 border border-gray-600">
            <h3 className="text-lg font-bold text-white mb-4">💥 Blast Radius Metrics</h3>
            
            <div className="space-y-3">
              {Object.entries(blastRadiusMetrics).map(([metric, value], index) => {
                if (metric === 'averageRadius') {
                  return (
                    <div key={index} className="text-center p-2 bg-gray-700 rounded">
                      <div className="text-white font-bold">{value}</div>
                      <div className="text-gray-400 text-xs">Average Radius</div>
                    </div>
                  );
                }
                return (
                  <div key={index} className="flex justify-between items-center p-2 bg-gray-700 rounded">
                    <span className="text-gray-300 capitalize text-sm">
                      {metric.replace(/([A-Z])/g, ' $1').trim()}
                    </span>
                    <div className="text-right">
                      <div className="text-white font-bold">{value.toFixed(1)}%</div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>

      {/* Chaos Timeline */}
      <div className="bg-gray-800 rounded-lg p-6 border border-gray-600">
        <h3 className="text-lg font-bold text-white mb-4">📋 Reliability Engineering Timeline</h3>
        
        <div className="space-y-2 max-h-60 overflow-y-auto">
          {chaosTimeline.map((event, index) => (
            <div key={index} className="flex items-start space-x-3 p-2 bg-gray-700 rounded border border-gray-600">
              <div className="text-gray-400 text-xs min-w-[60px]">{event.time}</div>
              <span className="text-lg">{getSeverityIcon(event.severity)}</span>
              <div className="flex-1 text-gray-300 text-sm">{event.event}</div>
              <div 
                className="px-2 py-1 rounded text-xs font-bold"
                style={{ 
                  backgroundColor: `${getStatusColor(event.type)}20`,
                  color: getStatusColor(event.type)
                }}
              >
                {event.type.toUpperCase()}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Status Footer */}
      <div className="bg-gray-800 rounded-lg p-4 border border-gray-600">
        <div className="flex justify-between items-center text-xs text-gray-400">
          <div>Advanced Reliability Engineering • v6.0 • Chaos + Synthetic + Resilience</div>
          <div>Overall Score: {reliabilityScores.overall.toFixed(1)} • Blast Radius: {blastRadiusMetrics.averageRadius}</div>
          <div className="flex items-center space-x-2">
            <div className="w-2 h-2 bg-red-400 rounded-full animate-pulse"></div>
            <span>CHAOS ENGINEERING ACTIVE</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdvancedReliabilityEngineeringCenter;